# Generated by Django 5.1.3 on 2024-11-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('CustomerName', models.CharField(max_length=50)),
                ('LoanNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('LoanAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('InterestRate', models.FloatField()),
                ('LoanStartDate', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
